# Generated by Django 4.0.3 on 2022-03-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la famille')),
            ],
            options={
                'verbose_name': 'famille',
                'verbose_name_plural': 'familles',
                'db_table': 'famille',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'aliment")),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliments', to='aliment.famille', verbose_name="Famille de l'aliment")),
            ],
            options={
                'verbose_name': 'aliment',
                'verbose_name_plural': 'aliments',
                'db_table': 'aliment',
                'ordering': ['name'],
            },
        ),
    ]
