# Generated by Django 4.0.3 on 2022-03-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='famille',
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='aliment.famille', verbose_name='Famille de la catégorie')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'db_table': 'categorie',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aliment',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliments', to='aliment.categorie', verbose_name="Catégorie de l'aliment"),
        ),
    ]
