# Generated by Django 4.0.3 on 2022-03-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0002_remove_aliment_famille_categorie_aliment_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aliment',
            new_name='M_aliment',
        ),
        migrations.RenameModel(
            old_name='Categorie',
            new_name='M_categorie',
        ),
        migrations.RenameModel(
            old_name='Famille',
            new_name='M_famille',
        ),
    ]
